### ISSUE TITLE
Categories link troubles in GitHubPages

### ISSUE THREAD

**Issue by nnise** [CloudCannon/frisco-jekyll-template#4]
hello,
Thanks for this template. I would like to use it as a base for my website, especially because of the categories implementation. I run it locally and everything works as in the demo, I mean I can see the pages of categories, for example:
https://brave-submarine.cloudvent.net/category/friendship/

but when I upload it here, to GitHub, I get the 404 error page: https://nnise.github.io/DenniseCBA/category/friendship/
All the other links work.
Any ideas of this error?  I have tried to change the url and base url and building the site again afterwards without success.

Thank you in advance!
Dennise

**Comment by mneumegen** [comment]
Hi @nnise ,

Unfortunately GitHub Pages doesn't support custom plugins. We use a plugin to generate these category pages.

**Comment by nnise** [comment]
Thanks for the explanation @mneumegen . After some headache yesterday now it makes sense. I would take another route then. 
All the best,
Dennise
