### ISSUE TITLE
Resizing the Site Logo

### ISSUE THREAD

**Issue by techlanka** [CloudCannon/frisco-jekyll-template#8]
Hi how do I resize the site logo in the top left corner, i tried changing the _layout/default.html the width ans height, but it does not take effect.

> <span class="dark-logo"><img width="104" height="45" src="{{ site.baseurl }}/images/logo/dark.svg" alt="dark madina logo"></span>

**Comment by attibalazs** [comment]
had the same issue, drove me crazy found it in the css eventually, change the height here:

layout.scss

```
	.company-name {
		font-size: 1.7em;
		display: inline-block;

		img {
			height: 30px;
			width: auto;
		}
	}
```
